<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Arzenal_Store_Client_WPF</RootNamespace>
	<AssemblyName>Arzenal-Store-Client-WPF</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Poppins-Black.ttf" />
    <None Remove="Fonts\Poppins-BlackItalic.ttf" />
    <None Remove="Fonts\Poppins-Bold.ttf" />
    <None Remove="Fonts\Poppins-BoldItalic.ttf" />
    <None Remove="Fonts\Poppins-ExtraBold.ttf" />
    <None Remove="Fonts\Poppins-ExtraBoldItalic.ttf" />
    <None Remove="Fonts\Poppins-ExtraLight.ttf" />
    <None Remove="Fonts\Poppins-ExtraLightItalic.ttf" />
    <None Remove="Fonts\Poppins-Italic.ttf" />
    <None Remove="Fonts\Poppins-Light.ttf" />
    <None Remove="Fonts\Poppins-LightItalic.ttf" />
    <None Remove="Fonts\Poppins-Medium.ttf" />
    <None Remove="Fonts\Poppins-MediumItalic.ttf" />
    <None Remove="Fonts\Poppins-Regular.ttf" />
    <None Remove="Fonts\Poppins-SemiBold.ttf" />
    <None Remove="Fonts\Poppins-SemiBoldItalic.ttf" />
    <None Remove="Fonts\Poppins-Thin.ttf" />
    <None Remove="Fonts\Poppins-ThinItalic.ttf" />
    <None Remove="Ressources\Image\AppConfirm.ico" />
    <None Remove="Ressources\Image\Warning.ico" />
    <None Remove="Ressources\success.html" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Ressources\ComboBox.xaml" />
    <Page Remove="Ressources\Template.xaml" />
    <Page Remove="Ressources\Template\AppDetailTemplate.xaml" />
    <Page Remove="Ressources\Template\AppTemplate.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Ressources\success.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
    <PackageReference Include="MySql.Data" Version="9.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Poppins-Black.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-BlackItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-BoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-ExtraBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-ExtraBoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-ExtraLight.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-ExtraLightItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-Italic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-Light.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-LightItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-MediumItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <EmbeddedResource Include="Fonts\Poppins-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Resource Include="Fonts\Poppins-SemiBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-SemiBoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-Thin.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Poppins-ThinItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\ComboBox.xaml" />
    <Resource Include="Ressources\Fonts\Poppins-Black.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-BlackItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-BoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ExtraBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ExtraBoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ExtraLight.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ExtraLightItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Italic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Light.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-LightItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-MediumItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-SemiBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-SemiBoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Thin.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ThinItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Image\Warning.ico" />
    <Resource Include="Ressources\Template\AppDetailTemplate.xaml" />
    <Resource Include="Ressources\Template\AppTemplate.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Arzenal-Store-Shared-Dtos">
      <HintPath>..\..\Arzenal-Store-Shared-Dtos\Arzenal-Store-Shared-Dtos\bin\Debug\net8.0\Arzenal-Store-Shared-Dtos.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
