<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Ressources\Image\AppConfirm.ico" />
    <None Remove="Ressources\Image\Warning.ico" />
    <None Remove="Ressources\success.html" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Ressources\ComboBox.xaml" />
    <Page Remove="Ressources\Template.xaml" />
    <Page Remove="Ressources\Template\AppDetailTemplate.xaml" />
    <Page Remove="Ressources\Template\AppTemplate.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Ressources\success.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Arzenal-Store-Shared-Dtos" Version="1.0.5" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
    <PackageReference Include="Microsoft.NETCore.Jit" Version="2.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" Version="19.225.1" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.Formats.Asn1" Version="10.0.5" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="Uno.UI" Version="5.6.99" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arzenal.StoreManager.ViewModels\Arzenal.StoreManager.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Ressources\ComboBox.xaml" />
    <Resource Include="Ressources\Fonts\Poppins-Black.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-BlackItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-BoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ExtraBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ExtraBoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ExtraLight.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ExtraLightItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Italic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Light.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-LightItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-MediumItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-SemiBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-SemiBoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-Thin.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Fonts\Poppins-ThinItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Ressources\Image\Warning.ico" />
    <Resource Include="Ressources\Template\AppDetailTemplate.xaml" />
    <Resource Include="Ressources\Template\AppTemplate.xaml" />
  </ItemGroup>



</Project>
