<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Arzenal-Store-Shared-Dtos\Arzenal-Store-Shared-Dtos\Arzenal.Dto.csproj" />
    <ProjectReference Include="..\ArzenalStoreManager.Data\Arzenal.StoreManager.Data.csproj" />
  </ItemGroup>

</Project>
